"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const createUrl_1 = require("../controllers/createUrl");
const readUrl_1 = require("../controllers/readUrl");
const updateUrl_1 = require("../controllers/updateUrl");
const deleteUrl_1 = require("../controllers/deleteUrl");
const getAllUrls_1 = require("../controllers/getAllUrls");
const getShortenedUrl_1 = require("../controllers/getShortenedUrl");
const redirectUrl_1 = require("../controllers/redirectUrl");
const router = express_1.default.Router();
router.post("/shorten", createUrl_1.createUrl);
router.get("/all", getAllUrls_1.getAllUrls);
router.get("/get-short-url", getShortenedUrl_1.getShortenedUrl);
router.get("/:shortUrl", readUrl_1.readUrl);
router.put("/:shortUrl", updateUrl_1.updateUrl);
router.delete("/:shortUrl", deleteUrl_1.deleteUrl);
router.get("/r/:shortUrl", redirectUrl_1.redirectUrl);
exports.default = router;
