name: Publish npm Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Authenticate with GitHub Packages (using the token stored as a secret)
      - name: Authenticate with npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@khabzox:registry=https://npm.pkg.github.com" >> ~/.npmrc

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Publish the npm package
      - name: Publish npm Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
